export const SIGNUP_TEXT = {
  agent_code_label: "کد نمایندگی",
  agent_code_placeholder: "کد نمایندگی را وارد کنید",
  province_label: "استان",
  province_placeholder: "استان را انتخاب کنید",
  county_label: "شهر",
  county_placeholder: "شهر را انتخاب کنید",
  address: "آدرس",
  insurance_branch_label: "شعبه بیمه",
  insurance_branch_placeholder: "شعبه بیمه را انتخاب کنید",
  phone_label: "تلفن ثابت",
  phone_placeholder: "XXX-XXX",
  prefix_label: "پیش‌شماره",
  prefix_placeholder: "021",
  agent_type: "نوع نمایندگی",
  genuine: "حقیقی",
  legal: "حقوقی",
  register: "ثبت‌نام",
};
