export const SIGNUP_TEXT = {
  representation_code_label: "کد نمایندگی",
  representation_code_placeholder: "کد نمایندگی را وارد کنید",
  province_label: "استان",
  province_placeholder: "استان را انتخاب کنید",
  city_label: "شهر",
  city_placeholder: "شهر را انتخاب کنید",
  address: "آدرس",
  insurance_branch_label: "شعبه بیمه",
  insurance_branch_placeholder: "شعبه بیمه را انتخاب کنید",
  phone_label: "تلفن ثابت",
  phone_placeholder: "XXX-XXX",
  prefix_label: "پیش‌شماره",
  prefix_placeholder: "021",
  representation_type: "نوع نمایندگی",
  genuine: "حقیقی",
  legal: "حقوقی",
  register: "ثبت‌نام",
};
